import day_11_cosmic_expansion.App;
import day_11_cosmic_expansion.Galaxy;
import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class GalaxyTest {
    @Test
    public void shouldCorrectlyExpandMap() throws IOException {
        var testGalaxy = App.loadTestInput("test_input.txt");
        var galaxy = new Galaxy(testGalaxy);
        galaxy.expandGalaxyMap();

        var expected = """
                ....#........
                .........#...
                #............
                .............
                .............
                ........#....
                .#...........
                ............#
                .............
                .............
                .........#...
                #....#.......
                """;

        assertEquals(galaxy.getMapAsString(), expected);
    }
}
