[workspace]
members = [ "day_10_pipe_maze","day_1_trebuchet", "day_2_cube_conundrum", "day_4_scratchcards", "day_6_wait_for_it", "day_7_camel_cards", "day_8_haunted_wasteland", "day_9_mirage_maintenance"]
resolver = "2"
